name: Build Fabric1
on:
#  schedule:
#    - cron: '0 0 * * *'
  workflow_dispatch:
env:
  DOCKER_NAMESPACE: mystery0
  SERVICE_NAME: fabric-mc
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: 下载Jar包
        run: |
          sudo apt-get update && sudo apt-get install -y wget curl jq
          sh fabricmc/pull.sh ${{ env.MINECRAFT_VERSION }}
          mv fabric-installer.jar fabricmc/fabric-installer.jar
          docker_image_tag=$(cat version.txt)
          echo "docker_image_tag=$docker_image_tag" >> $GITHUB_ENV
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - name: 登录私有仓库
        uses: docker/login-action@v3
        with:
          registry: ccr.docker.mystery0.vip
          username: ${{ secrets.REGISTRY_USERNAME1 }}
          password: ${{ secrets.REGISTRY_PASSWORD1 }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: fabricmc
          platforms: linux/amd64
          file: fabricmc/Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: ccr.docker.mystery0.vip/temp1/${{ env.SERVICE_NAME }}:${{ env.docker_image_tag }}
          no-cache: true