name: Auto-Green
on:
  workflow_dispatch:
    inputs:
      log:
        description: "Commit Log"
        required: true
        default: "每天不提交代码，心里就像有个未合并的分支，随时可能冲突"
        type: string
  schedule:
    - cron: "30 0 * * *"

jobs:
  autogreen:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Pull
        run: |
          git config --local user.name "Mystery0"
          git config --local user.email "mystery0dyl520@gmail.com"
          git remote set-url origin https://${{ github.repository_owner }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git pull --rebase
      - name: Commit
        run: git commit --allow-empty -m "${{ github.event.inputs.log || '每天不提交代码，心里就像有个未合并的分支，随时可能冲突' }}"
      - name: Push
        run: git push