name: Build Paper
on:
#  schedule:
#    - cron: '0 0 * * *'
  workflow_dispatch:
env:
  DOCKER_NAMESPACE: mystery0
  SERVICE_NAME: papermc
  MINECRAFT_VERSION: 1.21.1
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: 下载Jar包
        run: |
          sudo apt-get update && sudo apt-get install -y wget curl jq
          sh papermc/pull.sh ${{ env.MINECRAFT_VERSION }}
          mv paper.jar papermc/paper.jar
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - name: 登录私有仓库
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: papermc
          platforms: linux/amd64
          file: papermc/Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: ${{ env.DOCKER_NAMESPACE }}/${{ env.SERVICE_NAME }}:${{ env.MINECRAFT_VERSION }}
          no-cache: true